name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        brew: git lmod rc
        apt: git lmod rc
        choco: git rc

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        VIRTUAL_ENV=`dirname $(dirname $(which pip))` poetry install --with dev

    - name: Lint with mypy
      run: |
        mypy aurl

    - name: Test with pytest
      run: |
        pytest --cov aurl tests

    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.11 && startsWith(matrix.os, 'ubuntu')
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
